## Laboratorio 4
### Participantes
<ul>
    <li> Marisa Montoya 19169 </li>
    <li> Majo Morales 19145 </li>
    <li> Luis Garcia 19344 </li>

In [6]:
from sklearn import datasets
data = sklearn.datasets.make_classification(n_samples=50, n_features=3, n_informative=3, n_redundant=0, n_classes=2)

data


(array([[ 1.50277704e+00,  7.32792269e-01,  8.02185292e-01],
        [-1.28856280e+00, -1.54018590e+00, -5.46833520e-02],
        [-1.88602604e+00, -3.14535592e-02, -1.45619543e-01],
        [-5.28642836e-01,  2.30542690e-01, -1.09195104e+00],
        [-1.23045897e+00,  2.88400444e-01,  1.19864471e+00],
        [-1.77244439e-01,  1.21824337e+00, -1.48262638e+00],
        [-1.37846015e-01,  3.64354298e-01, -1.78027767e+00],
        [-5.49617209e-01,  4.18900992e-01, -1.50029787e+00],
        [ 7.11249900e-01,  8.35362586e-01,  7.93803500e-01],
        [-2.28712516e+00, -1.91603845e+00,  3.30721241e-01],
        [-2.12681800e+00, -4.99205774e-01,  3.27852154e+00],
        [-1.92141342e-01, -2.08962962e-03, -8.26680897e-01],
        [-2.92267794e+00, -4.70702491e-01,  1.53494243e+00],
        [-1.53984576e+00,  4.46104154e-01,  1.61424904e+00],
        [-1.52574879e+00,  1.46280850e-01,  5.68772933e-01],
        [-7.87999465e-01,  2.41276980e+00,  8.16924315e-01],
        [ 1.04270342e-01

In [10]:
X = data[0]
Y = data[1]


50

In [11]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=20, random_state=4)


In [13]:
# Initialize variables
learning_rate = 0.1
iterations = 5000
N = y_train.size

# number of input features
input_size = 3

# number of hidden layers neurons
hidden_size = 2 

# number of neurons at the output layer
output_size = 3  

results = pd.DataFrame(columns=["mse", "accuracy"])

In [14]:
# Initialize weights
np.random.seed(10)

# initializing weight for the hidden layer
W1 = np.random.normal(scale=0.5, size=(input_size, hidden_size))   

# initializing weight for the output layer
W2 = np.random.normal(scale=0.5, size=(hidden_size , output_size)) 

In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def mean_squared_error(y_pred, y_true):
    return ((y_pred - y_true)**2).sum() / (2*y_pred.size)
    
def accuracy(y_pred, y_true):
    acc = y_pred.argmax(axis=1) == y_true.argmax(axis=1)
    return acc.mean()

In [20]:
for itr in range(iterations):    
    
    # feedforward propagation
    # on hidden layer
    Z1 = np.dot(X_train, W1)
    A1 = sigmoid(Z1)

    # on output layer
    Z2 = np.dot(A1, W2)
    A2 = sigmoid(Z2)
    
    print(A2)

    # Calculating error
    mse = mean_squared_error(A2, y_train)
    acc = accuracy(A2, y_train)
    results=results.append({"mse":mse, "accuracy":acc},ignore_index=True )
    
    # backpropagation
    E1 = A2 - y_train
    dW1 = E1 * A2 * (1 - A2)

    E2 = np.dot(dW1, W2.T)
    dW2 = E2 * A1 * (1 - A1)

    
    # weight updates
    W2_update = np.dot(A1.T, dW1) / N
    W1_update = np.dot(X_train.T, dW2) / N

    W2 = W2 - learning_rate * W2_update
    W1 = W1 - learning_rate * W1_update


[[0.5044963  0.51718216 0.53670452]
 [0.5137487  0.51354845 0.51916948]
 [0.49991827 0.52120438 0.55062702]
 [0.51232064 0.54717452 0.59990658]
 [0.4995202  0.51865446 0.54495634]
 [0.49291928 0.53328999 0.58565589]
 [0.50638732 0.52957619 0.5642911 ]
 [0.49324114 0.53901835 0.59865506]
 [0.49720023 0.52121084 0.55322675]
 [0.50923842 0.51397622 0.52452021]
 [0.50643928 0.53500189 0.57700672]
 [0.50224456 0.52111855 0.54820929]
 [0.49961499 0.52185467 0.5524564 ]
 [0.49734451 0.53941075 0.59576784]
 [0.5079172  0.52641221 0.55536246]
 [0.50898831 0.54532196 0.59869383]
 [0.50980796 0.53930585 0.58393009]
 [0.49778675 0.53375994 0.58220545]
 [0.50187155 0.52738183 0.56338401]
 [0.50461722 0.54036282 0.5912322 ]
 [0.50658296 0.53168512 0.56907702]
 [0.50800022 0.52679804 0.55619713]
 [0.48888928 0.53370765 0.59038259]
 [0.51091546 0.52229981 0.5427481 ]
 [0.50649145 0.5335783  0.5736159 ]
 [0.49592298 0.53206865 0.57999581]
 [0.50125203 0.52241924 0.55223764]
 [0.51060935 0.52908455 0.55

ValueError: operands could not be broadcast together with shapes (30,3) (30,) 