## Laboratorio 4
### Participantes
<ul>
    <li> Marisa Montoya 19169 </li>
    <li> Majo Morales 19145 </li>
    <li> Luis Garcia 19344 </li>

In [2]:
from sklearn import datasets
data = datasets.make_classification(n_samples=50, n_features=3, n_informative=3, n_redundant=0, n_classes=2)

data


(array([[-1.18533278,  0.12237949, -0.83328518],
        [ 1.42779841, -1.21148644, -0.4613982 ],
        [-0.64720576,  0.6277383 ,  0.66474305],
        [ 1.68307495,  0.86862674, -0.34625972],
        [-1.01010376,  2.39219422, -0.97891845],
        [ 1.59054394,  1.64600605, -1.56744637],
        [ 0.34614084,  1.36336534,  0.70648817],
        [ 1.68493215, -1.33118183, -0.00720934],
        [-1.57191719, -0.08428239,  1.04242276],
        [ 0.5065725 , -0.5284    , -1.97532062],
        [-1.58296149,  1.2064179 ,  1.50693813],
        [-2.23081832,  0.36762312,  1.35166138],
        [-1.11259108,  1.24920553,  0.18266492],
        [-0.85516559,  1.23213627, -0.50132039],
        [ 1.00974321,  2.11911058,  0.16441713],
        [-1.67956815, -0.81835749, -0.86460777],
        [-0.63573684,  1.61405569, -0.28529528],
        [ 0.18484653, -1.03141469, -1.81486139],
        [-1.50642932,  1.05020194,  0.90977812],
        [-0.53385575,  2.02342126, -2.51868754],
        [ 0.65260655

In [3]:
X = data[0]
Y = data[1]


In [4]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=20, random_state=4)


In [52]:
train = np.column_stack((X_train,y_train))
train

array([[-0.85516559,  1.23213627, -0.50132039,  0.        ],
       [-1.58296149,  1.2064179 ,  1.50693813,  1.        ],
       [-0.53385575,  2.02342126, -2.51868754,  0.        ],
       [ 0.9237696 ,  2.12931439,  0.81798058,  1.        ],
       [ 0.54949583, -1.57246659, -0.68814238,  0.        ],
       [-1.37240742, -0.45157921, -0.2153139 ,  0.        ],
       [-0.89132941,  2.64362856, -1.50364945,  0.        ],
       [-1.84017865, -2.23321514,  2.04520519,  0.        ],
       [ 0.18484653, -1.03141469, -1.81486139,  0.        ],
       [-1.50542704,  0.90203236,  1.76803686,  1.        ],
       [ 0.93145153,  1.80753222, -0.59662946,  1.        ],
       [ 1.00974321,  2.11911058,  0.16441713,  1.        ],
       [-0.64720576,  0.6277383 ,  0.66474305,  1.        ],
       [ 0.86267082, -1.14569361, -0.8403325 ,  0.        ],
       [ 1.83734563, -1.6094072 ,  0.34759799,  0.        ],
       [-0.39069935, -1.02291344, -2.24536249,  0.        ],
       [-1.18533278,  0.

In [57]:
test = np.column_stack((X_test,y_test))
test

array([[ 0.34614084,  1.36336534,  0.70648817,  1.        ],
       [ 0.78103884, -0.13772585, -1.07328642,  1.        ],
       [-2.23081832,  0.36762312,  1.35166138,  1.        ],
       [-1.01010376,  2.39219422, -0.97891845,  0.        ],
       [-1.11259108,  1.24920553,  0.18266492,  1.        ],
       [ 0.24549629,  0.3179289 , -0.83219069,  1.        ],
       [ 1.68493215, -1.33118183, -0.00720934,  0.        ],
       [ 1.56340526, -1.48027745,  0.06667242,  0.        ],
       [-0.97346464,  0.59139125,  1.14176475,  1.        ],
       [-1.50642932,  1.05020194,  0.90977812,  1.        ],
       [-0.55198869,  3.88281659, -4.60709811,  0.        ],
       [ 2.8685301 ,  1.4729876 ,  0.07635276,  1.        ],
       [ 1.49198387, -0.99622776, -0.38840148,  0.        ],
       [-1.67956815, -0.81835749, -0.86460777,  0.        ],
       [-0.63573684,  1.61405569, -0.28529528,  0.        ],
       [ 0.58676359, -0.42106708, -2.05577337,  0.        ],
       [ 0.30187502,  0.

In [40]:
# Initialize a network
def initialize_network(n_inputs, n_hidden, n_outputs):
	network = list()
	hidden_layer = [{'weights':[random() for i in range(n_inputs + 1)]} for i in range(n_hidden)]
	network.append(hidden_layer)
	output_layer = [{'weights':[random() for i in range(n_hidden + 1)]} for i in range(n_outputs)]
	network.append(output_layer)
	return network

from random import seed
from random import random



In [30]:
# Calculate neuron activation for an input
def activate(weights, inputs):
	activation = weights[-1]
	for i in range(len(weights)-1):
		activation += weights[i] * inputs[i]
	return activation

In [32]:
# Transfer neuron activation
def transfer(activation):
	return 1.0 / (1.0 + exp(-activation))

In [33]:
# Forward propagate input to a network output
def forward_propagate(network, row):
	inputs = row
	for layer in network:
		new_inputs = []
		for neuron in layer:
			activation = activate(neuron['weights'], inputs)
			neuron['output'] = transfer(activation)
			new_inputs.append(neuron['output'])
		inputs = new_inputs
	return inputs

In [34]:
from math import exp

# Calculate neuron activation for an input
def activate(weights, inputs):
	activation = weights[-1]
	for i in range(len(weights)-1):
		activation += weights[i] * inputs[i]
	return activation

# Transfer neuron activation
def transfer(activation):
	return 1.0 / (1.0 + exp(-activation))

# Forward propagate input to a network output
def forward_propagate(network, row):
	inputs = row
	for layer in network:
		new_inputs = []
		for neuron in layer:
			activation = activate(neuron['weights'], inputs)
			neuron['output'] = transfer(activation)
			new_inputs.append(neuron['output'])
		inputs = new_inputs
	return inputs

# test forward propagation
network = [[{'weights': [0.13436424411240122, 0.8474337369372327, 0.763774618976614]}],
		[{'weights': [0.2550690257394217, 0.49543508709194095]}, {'weights': [0.4494910647887381, 0.651592972722763]}]]
row = [1, 0, None]
output = forward_propagate(network, row)
print(output)

[0.6629970129852887, 0.7253160725279748]


In [35]:
# Calculate the derivative of an neuron output
def transfer_derivative(output):
	return output * (1.0 - output)

In [36]:
# Backpropagate error and store in neurons
def backward_propagate_error(network, expected):
	for i in reversed(range(len(network))):
		layer = network[i]
		errors = list()
		if i != len(network)-1:
			for j in range(len(layer)):
				error = 0.0
				for neuron in network[i + 1]:
					error += (neuron['weights'][j] * neuron['delta'])
				errors.append(error)
		else:
			for j in range(len(layer)):
				neuron = layer[j]
				errors.append(neuron['output'] - expected[j])
		for j in range(len(layer)):
			neuron = layer[j]
			neuron['delta'] = errors[j] * transfer_derivative(neuron['output'])

In [37]:
# Update network weights with error
def update_weights(network, row, l_rate):
	for i in range(len(network)):
		inputs = row[:-1]
		if i != 0:
			inputs = [neuron['output'] for neuron in network[i - 1]]
		for neuron in network[i]:
			for j in range(len(inputs)):
				neuron['weights'][j] -= l_rate * neuron['delta'] * inputs[j]
			neuron['weights'][-1] -= l_rate * neuron['delta']

In [38]:
# Train a network for a fixed number of epochs
def train_network(network, train, l_rate, n_epoch, n_outputs):
	for epoch in range(n_epoch):
		sum_error = 0
		for row in train:
			outputs = forward_propagate(network, row)
			expected = [0 for i in range(n_outputs)]
			expected[row[-1]] = 1
			sum_error += sum([(expected[i]-outputs[i])**2 for i in range(len(expected))])
			backward_propagate_error(network, expected)
			update_weights(network, row, l_rate)
		print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))

In [55]:
from math import exp
from random import seed
from random import random

# Initialize a network
def initialize_network(n_inputs, n_hidden, n_outputs):
	network = list()
	hidden_layer = [{'weights':[random() for i in range(n_inputs + 1)]} for i in range(n_hidden)]
	network.append(hidden_layer)
	output_layer = [{'weights':[random() for i in range(n_hidden + 1)]} for i in range(n_outputs)]
	network.append(output_layer)
	return network

# Calculate neuron activation for an input
def activate(weights, inputs):
	activation = weights[-1]
	for i in range(len(weights)-1):
		activation += weights[i] * inputs[i]
	return activation

# Transfer neuron activation
def transfer(activation):
	return 1.0 / (1.0 + exp(-activation))

# Forward propagate input to a network output
def forward_propagate(network, row):
	inputs = row
	for layer in network:
		new_inputs = []
		for neuron in layer:
			activation = activate(neuron['weights'], inputs)
			neuron['output'] = transfer(activation)
			new_inputs.append(neuron['output'])
		inputs = new_inputs
	return inputs

# Calculate the derivative of an neuron output
def transfer_derivative(output):
	return output * (1.0 - output)

# Backpropagate error and store in neurons
def backward_propagate_error(network, expected):
	for i in reversed(range(len(network))):
		layer = network[i]
		errors = list()
		if i != len(network)-1:
			for j in range(len(layer)):
				error = 0.0
				for neuron in network[i + 1]:
					error += (neuron['weights'][j] * neuron['delta'])
				errors.append(error)
		else:
			for j in range(len(layer)):
				neuron = layer[j]
				errors.append(neuron['output'] - expected[j])
		for j in range(len(layer)):
			neuron = layer[j]
			neuron['delta'] = errors[j] * transfer_derivative(neuron['output'])

# Update network weights with error
def update_weights(network, row, l_rate):
	for i in range(len(network)):
		inputs = row[:-1]
		if i != 0:
			inputs = [neuron['output'] for neuron in network[i - 1]]
		for neuron in network[i]:
			for j in range(len(inputs)):
				neuron['weights'][j] -= l_rate * neuron['delta'] * inputs[j]
			neuron['weights'][-1] -= l_rate * neuron['delta']

# Train a network for a fixed number of epochs
def train_network(network, train, l_rate, n_epoch, n_outputs):
	for epoch in range(n_epoch):
		sum_error = 0
		for row in train:
			outputs = forward_propagate(network, row)
			expected = [0 for i in range(n_outputs)]
			expected[row[-1]] = 1
			sum_error += sum([(expected[i]-outputs[i])**2 for i in range(len(expected))])
			backward_propagate_error(network, expected)
			update_weights(network, row, l_rate)
		print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))

# Test training backprop algorithm
seed(1)
dataset = [[2.7810836,2.550537003,0],
	[1.465489372,2.362125076,0],
	[3.396561688,4.400293529,0],
	[1.38807019,1.850220317,0],
	[3.06407232,3.005305973,0],
	[7.627531214,2.759262235,1],
	[5.332441248,2.088626775,1],
	[6.922596716,1.77106367,1],
	[8.675418651,-0.242068655,1],
	[7.673756466,3.508563011,1]]
n_inputs = len(dataset[0]) - 1
n_outputs = len(set([row[-1] for row in dataset]))
network = initialize_network(n_inputs, 2, n_outputs)
train_network(network, dataset, 0.5, 20, n_outputs)
#for layer in network:
#	print(layer)

>epoch=0, lrate=0.500, error=6.350
>epoch=1, lrate=0.500, error=5.531
>epoch=2, lrate=0.500, error=5.221
>epoch=3, lrate=0.500, error=4.951
>epoch=4, lrate=0.500, error=4.519
>epoch=5, lrate=0.500, error=4.173
>epoch=6, lrate=0.500, error=3.835
>epoch=7, lrate=0.500, error=3.506
>epoch=8, lrate=0.500, error=3.192
>epoch=9, lrate=0.500, error=2.898
>epoch=10, lrate=0.500, error=2.626
>epoch=11, lrate=0.500, error=2.377
>epoch=12, lrate=0.500, error=2.153
>epoch=13, lrate=0.500, error=1.953
>epoch=14, lrate=0.500, error=1.774
>epoch=15, lrate=0.500, error=1.614
>epoch=16, lrate=0.500, error=1.472
>epoch=17, lrate=0.500, error=1.346
>epoch=18, lrate=0.500, error=1.233
>epoch=19, lrate=0.500, error=1.132


In [66]:
from math import exp

# Calculate neuron activation for an input
def activate(weights, inputs):
	activation = weights[-1]
	for i in range(len(weights)-1):
		activation += weights[i] * inputs[i]
	return activation

# Transfer neuron activation
def transfer(activation):
	return 1.0 / (1.0 + exp(-activation))

# Forward propagate input to a network output
def forward_propagate(network, row):
	inputs = row
	for layer in network:
		new_inputs = []
		for neuron in layer:
			activation = activate(neuron['weights'], inputs)
			neuron['output'] = transfer(activation)
			new_inputs.append(neuron['output'])
		inputs = new_inputs
	return inputs

# Make a prediction with a network
def predict(network, row):
	outputs = forward_propagate(network, row)
	return outputs.index(max(outputs))

# Test making predictions with the network
dataset = test
network = [[{'weights': [-1.482313569067226, 1.8308790073202204, 1.078381922048799]}, {'weights': [0.23244990332399884, 0.3621998343835864, 0.40289821191094327]}],
	[{'weights': [2.5001872433501404, 0.7887233511355132, -1.1026649757805829]}, {'weights': [-2.429350576245497, 0.8357651039198697, 1.0699217181280656]}]]
predictions = []
for row in dataset:
	prediction = predict(network, row)
	predictions.append(prediction)
	print('Expected=%d, Got=%d' % (row[-1], prediction))

Expected=1, Got=0
Expected=1, Got=1
Expected=1, Got=0
Expected=0, Got=0
Expected=1, Got=0
Expected=1, Got=0
Expected=0, Got=1
Expected=0, Got=1
Expected=1, Got=0
Expected=1, Got=0
Expected=0, Got=0
Expected=1, Got=1
Expected=0, Got=1
Expected=0, Got=0
Expected=0, Got=0
Expected=0, Got=1
Expected=1, Got=0
Expected=1, Got=0
Expected=1, Got=0
Expected=0, Got=1


In [70]:
real = []
for i in range(len(y_test)):
    real.append(y_test[i])
count = 0 
for i in range(len(real)):
    if (real[i]==predictions[i]):
        count = count + 1
ac
print ('accuracy score',)